name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Build with Maven
        run: mvn clean package
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Run Unit Tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # deploy commands (e.g., scp, SSH, etc.)
          echo "Deployment completed."

  e2e:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: End-to-End Testing
        run: |
          echo "Running E2E automation scripts..."
          # Pseudocode for automated end-to-end validation
          echo "E2E tests passed."
